version: "3"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: dup3kjfao
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=dup3kjfao
    env_file:
      - .env
    volumes:
      - nextjs_node_modules:/app/node_modules
    networks:
      - nextjs_network
    restart: unless-stopped

networks:
  nextjs_network:
    driver: bridge

volumes:
  nextjs_node_modules:
